Rename RossumPython to TxScript
rossumai/university pull request #355
Opened 2024-10-17 23:28 UTC by pasky

2024-10-21 11:22 UTC, mrtnzlml requested changes
Thank you very much for your contribution. There seem to be some unwanted (?) changes. Could you please have a look?

2024-10-21 11:22 UTC, mrtnzlml commented on docs/learn/rossum-formulas/index.md
> +substitute(t"[^0-9]", t"", field.document_id)  # Remove non-digit characters
```suggestion
substitute(r"[^0-9]", r"", field.document_id)  # Remove non-digit characters
```

2024-10-21 11:22 UTC, mrtnzlml commented on docs/learn/rossum-formulas/index.md
> +re.sub(t"[^0-9]", t"", field.document_id)
```suggestion
re.sub(r"[^0-9]", r"", field.document_id)
```

2024-10-21 11:22 UTC, mrtnzlml commented on docs/learn/rossum-formulas/index.md
> +substitute(t"[^0-9]", t"", field.document_id)
```suggestion
substitute(r"[^0-9]", r"", field.document_id)
```

2024-10-25 07:18 UTC, mrtnzlml approved these changes

2024-10-27 14:02 UTC, pasky commented
Thanks for catching these, sorry about that!

2024-10-27 14:12 UTC, merged